name: Build & Deploy Website

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install Dependencies
      run: npm install
    - name: Build Website
      run: npx @11ty/eleventy
      env:
        CTF_SPACE_ID: ${{ secrets.CTF_SPACE_ID }}
        CTF_CDA_ACCESS_TOKEN: ${{ secrets.CTF_CDA_ACCESS_TOKEN }}
    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Website
        id: deployment
        uses: actions/deploy-pages@v4
